version: 2.1
orbs:
  sonarcloud: sonarsource/sonarcloud@1.0.2
jobs:
  example-job:
    docker:
      # replace with your preferred image
      - image: cimg/base:stable
    steps:
      - sonarcloud/scan:
          cache_version: 1 
          sonar_token_variable_name: SONAR_TOKEN 

workflows:
  example-workflow:
    jobs:
      - example-job