version: 2.1
orbs:
  vulnerability-checker: whitesource/vulnerability-checker@19.10.1

workflows:
    example-workflow:
      jobs:
        - vulnerability-checker/scan:
            directory: . 

          